import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
// import styles from "../styles/Home.module.css";
import Link from "next/link";
import Navigation from "../Components/Navigation";
import Button from "../Components/Button";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Imaginerium</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main>
        <h1>Imaginerium</h1>
        <p>
          Imaginerium is a place where you can create your own characters and
          share them with the world.
        </p>
        <div>
          <Button text="Create character" src={"/createCharacter"}></Button>
          <Button text="Character list" src={"/characterList"}></Button>
        </div>
      </main>
    </>
  );
}
